### ISSUE TITLE
Human-readable explanations of validation errors?

### ISSUE THREAD

**Issue by aviflax** [juxt/jinx#16]
Hi, are there any plans to add such a feature to this library?

I took a look at the tests and as far as I can tell, when `validate` finds an invalid value, it simply returns `false` and the invalid value, but there’s no error message as a string, no path to the problematic value from the root value passed in, and no reference to the specific schema that triggered the failure.

I could be mistaken about all of that, but if so I’d love to be corrected! And if I’m right, I’d love to learn whether any thought has been put to how useful and actionable error messages for end-users (i.e. people authoring/constructing values) might be constructed.

Thank you!

**Comment by malcolmsparks** [comment]
Hi @aviflax  - jinx returns a document for each validation call, with an entry of `:valid?` if the document is valid, and an entry with a list of errors if not valid.

There's still some work to do on improving the error messages, however.

**Comment by aviflax** [comment]
OK, thanks!
